### ISSUE TITLE
question: modify logo

### ISSUE THREAD

**Issue by yonj1e** [janczizikow/sleek#27]
how to modify logo? the svg on the left of the header (the one that says "sleek").
What software did you use to generate it?

**Comment by janczizikow** [comment]
Hey @yonj1e,

I used [sketch](https://www.sketchapp.com/) to create the logo. You can see the details in [this issue](#1). To modify it you replace the `_includes/logo.svg` with your own svg file or change the code inside `_includes/header.html`. since I'm getting this question a lot perhaps I can also make some adjustments to make it easier for the users of the theme to change the logo through settings in `_config.yml`.
