### ISSUE TITLE
Mathjax or Katex support 

### ISSUE THREAD

**Issue by rahulpathakml** [janczizikow/sleek#4]
Hi Jan,
Can you please add mathjax/katex support in sleek. Though I don't know much HTML/CSS, I tried to add mathjax but it does not display inline math properly (equation is not aligned to line text).

![screenshot-2018-2-5 example content](https://user-images.githubusercontent.com/23165276/35801323-e68395a2-0a91-11e8-9c54-8b51073c97da.png)

**Comment by janczizikow** [comment]
Hey @rahulpathakml, 

To be honest with you I never heard about mathjax/katex before. Luckily turns out it's quite is to add to jekyll blog. I followed [this blog post](http://sgeos.github.io/github/jekyll/2016/08/21/adding_mathjax_to_a_jekyll_github_pages_blog.html) and added mathjax support to the theme you can find the 'how to' guide [here](https://janczizikow.github.io/sleek/getting-started/#mathjax). Let me know if that helps!

**Comment by rahulpathakml** [comment]
Its good enough for me.
