### ISSUE TITLE
how to get main.css to update?

### ISSUE THREAD

**Issue by nsteinme** [janczizikow/sleek#44]
Sorry, I'm sure this is a beginner question, but I am trying to update the css on the hero image (increase transparency a bit) and when I edit /_sass/pages/_page.scss the changes don't seem to get incorporated into /assets/css/main.css. How do I get this to "build" properly, or do I need to edit main.css directly? 

I'm running the site by forking your repo (here: https://github.com/SteinmetzLab/SteinmetzLab.github.io) and using github pages. 

Thanks!

**Comment by janczizikow** [comment]
Hey @nsteinme ,

All the files form `_sass` are compiled by [gulp](https://github.com/gulpjs/gulp) so you have to run `gulp sass` from the command line in the root directory of your project. alternatively  you can just run `gulp` instead of normal jekyll command to build jekyll server and hot-reload all the changes to css / js

Hope that helps!

**Comment by nsteinme** [comment]
Excellent, yes, that worked, sorry I missed that!
