### ISSUE TITLE
The hero img looks strange on high resolution display

### ISSUE THREAD

**Issue by TonnyL** [janczizikow/sleek#47]
<img width="2652" alt="screen shot 2018-09-15 at 2 38 17 pm" src="https://user-images.githubusercontent.com/13329148/45583482-b223f780-b8f5-11e8-8b63-85a3ccba108b.png">

**Comment by janczizikow** [comment]
Hmm not really sure what's strange? You mean the font is too small?

**Comment by TonnyL** [comment]
No. It seems that the hero-image was cropped when comparing to a it self on a iPad.

BTW, I am not a front-end developer, if I asked a silly question, don't be angry 😂.

**Comment by janczizikow** [comment]
No worries, it's adjusting because of `background-position: 50%`  and height constrain CSS in `_sass/pages/page.scss`. If you want you can adjust height property on line 13 to a bigger value, so that on larger breakpoints the image is larger. You can play around in your browser dev-tools to find a value that would hit the right spot for you 🙂

**Comment by TonnyL** [comment]
@janczizikow Many thanks to you, I'll try it.
