### ISSUE TITLE
changing favicon doesnt seem to work

### ISSUE THREAD

**Issue by MadeByDouglas** [janczizikow/sleek#7]
so i replaced the image files, including say favicon.ico, but now it just doesnt load any.

when i look at head.html at this line,   `<link rel="shortcut icon" href="{{ '/assets/img/icons/favicon.ico?v=qA3OXqyw77' | relative_url }}">`
I'm not sure why the `v=qA3OXqyw77` is added. its for each type of favicon. Even if i change to png (and also favicon.png) doesnt seem to work. Any advice?

Also there are meta tags that still say "sleek" here, would be nice to have them updated to the title in the _config.yml file, so i guess that would look like `{{_config.title}}` ? I'm still not totally sure of the syntax here.

**Comment by janczizikow** [comment]
The ``v=qA3OXqyw77`` is added to overwrite previously cached favicons. I think if you replace a favicon in the code with a new favicon (with the same name) it might still be cached in your browser. So to avoid that you can add a unique parameter to the favicon, so that the icon gets replace immediately. You can checkout [this website](https://realfavicongenerator.net/) - it can generate all the favicons and give you code & files, which you could simply copy & paste.

**Comment by janczizikow** [comment]
Hey @MadeByDouglas closing this one as well, let me know if this worked for you!
